#!/usr/bin/env python3
"""
FIDATI. (C64) - level data generator (Block 1: SPAZIO GEOMETRICO,
levels 1-3, transcribed verbatim from the original HTML5 source).

Emits ca65 .byte tables for:
  - a 240-byte (20x12) tile-type grid per level
  - spawn column/row per level
Tile types: 0 empty, 1 solid, 2 fake floor, 3 spike,
            4 flag(real), 5 flag(fake), 6 flag(ghost)
"""

COLS, ROWS = 20, 12

LEVELS = [
{"name":"FIDATI DEL PAVIMENTO", "map":[
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
".P................F.",
"#####..####..##fff##",
"#####..####..##...##",
]},
{"name":"LA SCORCIATOIA COMODA", "map":[
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"...ffffffffffffff...",
"....................",
"..#.................",
".P...^....^....^..F.",
"####################",
"####################",
]},
{"name":"LA BANDIERA E' LI'. GIURO.", "map":[
"....................",
"....................",
"....................",
".G..................",
"###.................",
"....................",
"......###...........",
"....................",
"..##................",
".P.........X........",
"###ff###..####..####",
"###..###..####..####",
]},
]

TYPE = {".":0, "#":1, "f":2, "^":3, "F":4, "X":5, "G":6, "P":0}

def emit():
    out = []
    out.append("; ---- AUTO-GENERATED by tools/gendata.py, do not hand-edit ----")
    for i, lvl in enumerate(LEVELS):
        m = lvl["map"]
        assert len(m) == ROWS, (i, len(m))
        spawn_c = spawn_r = None
        cells = []
        for r, row in enumerate(m):
            assert len(row) == COLS, (i, r, len(row))
            for c, ch in enumerate(row):
                if ch == "P":
                    spawn_c, spawn_r = c, r
                cells.append(TYPE[ch])
        assert spawn_c is not None, i
        out.append("level%d_grid:" % (i+1))
        for rbase in range(0, len(cells), 20):
            row_bytes = cells[rbase:rbase+20]
            out.append("    .byte " + ",".join(str(b) for b in row_bytes))
        out.append("level%d_spawn_col = %d" % (i+1, spawn_c))
        out.append("level%d_spawn_row = %d" % (i+1, spawn_r))
        out.append("")
    return "\n".join(out)

if __name__ == "__main__":
    print(emit())
