#!/usr/bin/env python3
"""
FIDATI. (C64) - text/string table generator.
Converts plain uppercase ASCII strings into C64 screen-code byte
tables (Pascal-style: length byte followed by the code bytes), since
the game's custom charset only carries the "upper/graphics" ROM font.
"""

def to_screencode(s):
    out = []
    for c in s:
        if 'A' <= c <= 'Z':
            out.append(ord(c) - ord('A') + 1)
        elif 32 <= ord(c) <= 63:
            out.append(ord(c))
        else:
            raise ValueError("unsupported char %r in %r" % (c, s))
    return out

STRINGS = [
 ("txt_title",        "FIDATI."),
 ("txt_subtitle",     "UN PLATFORM ONESTO AL 60%"),
 ("txt_credit",       "GAME DESIGN: CARLO GERLA"),
 ("txt_port",         "PORTING C64: CURSOR AGENT"),
 ("txt_howto1",       "JOYSTICK PORTA 2"),
 ("txt_howto2",       "SINISTRA/DESTRA MUOVE, FUOCO SALTA"),
 ("txt_press",        "PREMI FUOCO PER GIOCARE"),

 ("txt_hud_morti",    "MORTI:"),
 ("txt_hud_punti",    "PUNTI:"),
 ("txt_hud_blocco",   "BLOCCO 1/3"),
 ("txt_hud_liv",      "LIV"),

 ("txt_lvl1",         "FIDATI DEL PAVIMENTO"),
 ("txt_lvl2",         "LA SCORCIATOIA COMODA"),
 ("txt_lvl3",         "LA BANDIERA E' LI'. GIURO."),
 ("txt_theme",        "SPAZIO GEOMETRICO"),

 ("txt_fall1",        "IL PAVIMENTO ERA UN'OPINIONE."),
 ("txt_fall2",        "LA GRAVITA RINGRAZIA."),
 ("txt_fall3",        "FISICA 1 - TU 0."),
 ("txt_fall4",        "QUASI. CIOE, NO."),

 ("txt_spike1",       "C'ERA. SI VEDEVA. EPPURE."),
 ("txt_spike2",       "GLI SPUNTONI NON SI SCUSANO."),
 ("txt_spike3",       "PUNTO E A CAPO. LETTERALMENTE."),
 ("txt_spike4",       "NON DICEVO SUL SERIO. FORSE."),

 ("txt_xflag1",       "QUELLA BANDIERA ERA UNA DEMO."),
 ("txt_xflag2",       "FIDATI, DICEVANO."),
 ("txt_xflag3",       "IL MARKETING HA ESAGERATO."),
 ("txt_xflag4",       "ERA SOLO PER VEDERE SE CI CASCAVI."),

 ("txt_deaths_lbl",   "MORTI "),
 ("txt_retry",        "OK, RICOMINCIAMO."),

 ("txt_completed",    "LIVELLO COMPLETATO"),
 ("txt_gain_pre",     "+"),
 ("txt_gain_post",    " PUNTI"),
 ("txt_notrust",      "NON TI ABITUARE"),

 ("txt_block_done",   "BLOCCO 1 COMPLETATO"),
 ("txt_score_tot",    "PUNTI TOTALI:"),
 ("txt_deaths_tot",   "MORTI TOTALI:"),
 ("txt_restart",      "PREMI FUOCO PER RIGIOCARE"),
 ("txt_toblk2",       "IL BLOCCO 2 E' IN COSTRUZIONE."),
]

def emit():
    out = ["; ---- AUTO-GENERATED by tools/gentext.py, do not hand-edit ----"]
    for label, s in STRINGS:
        codes = to_screencode(s)
        out.append("%s:" % label)
        out.append("    .byte %d" % len(codes))
        for i in range(0, len(codes), 16):
            chunk = codes[i:i+16]
            out.append("    .byte " + ",".join(str(b) for b in chunk))
    return "\n".join(out)

if __name__ == "__main__":
    print(emit())
